### ISSUE TITLE
"Download" WebUI is different after "bower install" Command

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#1]
After running **bower install** in interface/ to reinstall the packages specified in **bower.json**, I noticed that the dynamic rows of annotation type names retrieved from the back end look different from the three rows of static annotation types. It doesn't seem to affect the functionality, though.

Probably need to tweak **download.tpl.html** to make all rows on web UI look consistent.

**Comment by mhuyck** [comment]
The static and dynamic parts *should* look a little different since the static ones cannot be changed, but I agree that the appearance could be refined a bit. Implementation suggestion: each row's HTML should be identical except for the use of a different CSS class to identify the static (or the non-static -- your choice!) rows.

**Comment by dongbohu** [comment]
Thanks for your comments. I am going to rewrite this module when I get time. There are some other places that I want to improve too.

**Comment by dongbohu** [comment]
Fixed.
