### ISSUE TITLE
Make sure code in gene/search.js does things in an 'Angular way'/ follows the Angular mantra. 

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#17]
This stems from the recommendations brought up by Matt in Pull Request #15. Specifically, we discussed the difference between scope.page and scope.pageDict.page in the searchButtonset, and using '$broadcast' and '$on' between the SearchResults factory and the directives.

**Comment by mhuyck** [comment]
Thank you for capturing this, @rzelayafavila! To elaborate on my questions a little, I'll just say that when I've found myself heading down a path that involves using the more advanced or esoteric features of Angular it has been because I've designed the view in a "non-Angularish" manner. By that I mean trying to apply an imperative style of coding in a context where Angular works more naturally in a "reactive" or "descriptive" manner. If I step back and try to think less about the control flow and more about the *appearance* of the page given the presence of particular data, then the elements of Angular tend to click into place much better. Although it required a substantial reorganization of code in my case, the end result was much cleaner and easier to follow.

That said, the more advanced Angular features are there for a reason. Sometimes we need to `$broadcast` signals and respond and that's the right design. Advice I've seen indicates that should be used sparingly, however.

**Comment by rzelayafavila** [comment]
Thanks for elaborating on this @mhuyck! This is very helpful to decide on how I will restructure some of this code and design code in the future!

**Comment by mhuyck** [comment]
Another spot in pull request 15 related to this question: what does calling `scope.updatePage()` in the `moreResultButton` directive within `app/gene/search.js` differ from updating scope.page and scope.pageDict.page?

**Comment by rzelayafavila** [comment]
All of this (Angularizing the gene search module, using inherited directive scopes instead of ``$broadcast`` and ``$on``, and streamlining the updating of the searchButtonset page) has been addressed in the gene search module as of Pull Request # 39.
