### ISSUE TITLE
Need to update README to include more clear instructions on setting up a deployment instance

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#187]
These items were discovered while setting up a deployment instance with @jaclyn-taroni. I will make smaller sub-issues to track the items that came up, and link them to this issue. 

- [x] https://github.com/greenelab/adage-server/issues/188
- [x] https://github.com/greenelab/adage-server/issues/189
- [x] https://github.com/greenelab/adage-server/issues/190
- [x] https://github.com/greenelab/adage-server/issues/191

**Comment by cgreene** [comment]
Manuscript reviewer comment:
"Please provide software stack along with instructions to initialize instance of the ADAGE web server so that users can load models of interest as mentioned in the manuscript"

Manuscript is due back Sept 28. Means that we probably need to have these things done ~2 weeks before. With the changes in the software deployment, this puts a very hard deadline on getting the containerization changes done. @rzelayafavila / @dongbohu

**Comment by rzelayafavila** [comment]
Ok, sounds good, so I'll aim to have the containerization all wrapped up by Sept. 15

**Comment by cgreene** [comment]
+ Instructions on how to initialize an instance! :smiley_cat:

**Comment by rzelayafavila** [comment]
Closed final sub-issue of this with the merging of https://github.com/greenelab/adage-server/pull/267
