### ISSUE TITLE
Gene-Gene Network Page: retain the network state when "back" button is clicked

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#305]
**Deepa feedback Priority 3**
Once the network is generated, the Signature details open in the tab. When the users hit the back button, the network is generated again and the position of the nodes is back to default positions. This can be a pain-point, especially if there are a lot of nodes and the user has invested time to move them around to positions which make sense for them. Also, if they are interested in comparing or viewing multiple signatures, they will have to keep moving back and forth between the two pages, which is just a lot of work and waiting. 

Recommendation: Open the signature details page in a new tab.

Dr. Deb Hogan also mentioned that she would like the network to be retained when clicking "back" button.

**Comment by mhuyck** [comment]
Consider adding parameters to capture the state of the "min edge weight" radio buttons and "max # of genes" slider so that link sharing preserves more of the state.

I guess these both will be needed if we are to try and preserve the positions of the nodes, but I thought I would explicitly call attention to that since it came up while discussing #315.

**Comment by mhuyck** [comment]
Another thought, while I am here: capturing the positions of all of the nodes could turn into a lot of data very fast. It is not clear to me that this could be done *solely* via parameters in the URL.

One option is to try and get clever with encoding so that node positions take up as few bits as possible and then convert that binary data into some efficient URL-encoded parameter (base64?) but I would guess that even that could rapidly hit [practical limits on URL length](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

Another approach is to use a link-shortening technique (think of the ubiquitous https://bitly.com), the essence of which is to store a mapping between the short URL's ID and the full URL in a database. In a similar fashion, we could save the graph's state as a record in a table designed to support this feature via a bitly-style ID. Some care would be needed to avoid letting that table grow out of hand while indefinitely preserving graphs that people want to share.

There might be other ways to go about this, but I thought I'd note these here since they came to mind.

**Comment by cgreene** [comment]
Let's make the link open in a new tab for 1.0.

**Comment by dongbohu** [comment]
Fixed in PR #342.
