### ISSUE TITLE
Allow network export to tab delimited and/or csv

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#347]
Deb Hogan would like to be able to get the genes and weights out of a network view as a tab delimited or CSV file.

In this case, it would get all of the edges in this network: http://adage.greenelab.com/#/gene_network/?genes=865,937,5403&mlmodel=1

In the format:
`Gene1,Gene2,Weight`

**Comment by dongbohu** [comment]
Considering that some gene names may not be unique, maybe we should also include gene's entrez ID.

**Comment by cgreene** [comment]
Ahh - what about this format to make sure that they get the unique ID (entrez) with the convenient name? `Gene1` here indicates the displayed name in the network:
`Gene1|Entrez,Gene2|Entrez,Weight`

This way, if someone processes it as CSV they still get as expected, but they can also separate on | if desired to get the synonyms split.

**Comment by mhuyck** [comment]
Note: this issue is a variant of #273 and #261. Seems like it would be very useful to have it implemented.

**Comment by cgreene** [comment]
Ahh - yea - this has been requested enough times that I think we could consider this a "very important feature."

**Comment by mhuyck** [comment]
This is currently implemented as described above: with pipes (`|`) separating gene labels from Entrez IDs. It looks funky to me in practice... I propose that we simply  make the Entrez IDs into separate columns, since it's a `.csv` file and needs to be parsed into columns anyway. Will check with the Hogan lab, too, to get their thoughts in case I'm missing something.

Demo site: http://greenelab.fgtech.com/#/gene_network/?genes=5403&mlmodel=1

**Comment by mhuyck** [comment]
Fixed in #350.
