### ISSUE TITLE
Supporting PatternMarker type "Participation" 

### ISSUE THREAD

**Issue by genesofeve** [greenelab/adage-server#58]
I see that you can have genes participate in nodes via `Participation` but it looks like the server only supports one participation type at a time. Can we generalize this by adding a type field? I'd like to be able to incorporate a PatternMarker type relationship as well.

**Comment by dongbohu** [comment]
For this generalization, here is a sketch of what needs to be done:

1. On the backend: 
* Add a new **ParticipationType** model in **models.py**, and a new django command to populate the corresponding table.
* Add `paticipation_type` field in `Participation` class in **models.py**, may also need to change the django command that populates the `Participation` table.

2. On the frontend, change the `High-weight genes` section of the **Node** page so that it will show the participation type, may need new widget on web UI to allow users to select participation type that they are interested in.

Due to other high priority tasks, this feature may not be implemented until after February, 2017.

**Comment by cgreene** [comment]
@genesofeve - the UI is now starting for this. See #160

**Comment by rzelayafavila** [comment]
Ok, all of the items for this issue have been completed with merging of PR #160. Thanks for suggesting this @genesofeve! This should be up when we do our next deployment of the web server at http://adage.greenelab.com, which will happen in the near future.
